apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # Number of backend pods
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: adi2634/backend-python:latest  # Replace with your actual image
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: "/app/Backend/config.json"
              subPath: "config.json"
      volumes:
        - name: config-volume
          configMap:
            name: config-json  # Mount from ConfigMap
