apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: adi2634/frontend-react:latest
          ports:
            - containerPort: 3600  # ✅  Should match the service targetPort
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config  # ✅ Using ConfigMap
                  key: REACT_APP_BACKEND_URL

